import type { IssueRecord } from '@/lib/types'

export const fallbackIssues: IssueRecord[] = [
  {
    id: 'fallback-001',
    documentId: 'CC-SAMPLE-001',
    title: 'Streetlight outage near market square',
    description:
      'Several streetlights near the market square have been out for over a week, creating safety concerns after sunset.',
    category: 'Public Lighting',
    department: 'Municipal Public Lighting',
    pin: '401208',
    locality: 'Market Square',
    status: 'In Progress',
    priority: 'High',
    trust: 84,
    chaiHeat: 86,
    supporters: 1432,
    reports: 26,
    comments: 41,
    daysUnresolved: 8,
    officer: 'Electrical Supervisor',
    hub: 'Ward Operations Hub',
    createdAt: '2026-08-22T10:00:00.000Z',
  },
  {
    id: 'fallback-002',
    documentId: 'CC-SAMPLE-002',
    title: 'Garbage collection delayed in residential lane',
    description:
      'Waste has not been collected regularly in the residential lane for the last three days, attracting pests and creating hygiene concerns.',
    category: 'Sanitation',
    department: 'Solid Waste Management',
    pin: '401209',
    locality: 'Residential Lane',
    status: 'Assigned',
    priority: 'Moderate',
    trust: 77,
    chaiHeat: 69,
    supporters: 946,
    reports: 19,
    comments: 28,
    daysUnresolved: 5,
    officer: 'Sanitary Inspector',
    hub: 'Ward Operations Hub',
    createdAt: '2026-08-25T08:30:00.000Z',
  },
  {
    id: 'fallback-003',
    documentId: 'CC-SAMPLE-003',
    title: 'Pothole near the school boundary',
    description:
      'A broken stretch of road near the school boundary is posing risk to school commuters and two-wheeler riders.',
    category: 'Roads & Potholes',
    department: 'PWD — Roads Division',
    pin: '401208',
    locality: 'School Boundary Road',
    status: 'Community Verified',
    priority: 'Critical',
    trust: 92,
    chaiHeat: 94,
    supporters: 2130,
    reports: 41,
    comments: 52,
    daysUnresolved: 12,
    officer: 'Junior Engineer',
    hub: 'Ward Operations Hub',
    createdAt: '2026-08-18T12:15:00.000Z',
  },
]
