import type { IssueRecord } from '@/lib/types'

export const seedIssues: IssueRecord[] = [
  {
    id: 'seed-001',
    documentId: 'CC-SEED-001',
    title: 'Streetlight outage near market square',
    description:
      'Several streetlights near the market square have been non-functional for more than a week, creating unsafe conditions after sunset.',
    category: 'Public Lighting',
    department: 'Municipal Public Lighting',
    pin: '401208',
    locality: 'Market Square',
    status: 'In Progress',
    priority: 'High',
    trust: 84,
    chaiHeat: 86,
    supporters: 1432,
    reports: 26,
    comments: 41,
    daysUnresolved: 8,
    officer: 'Electrical Supervisor',
    hub: 'Ward Operations Hub',
    createdAt: '2026-08-22T10:00:00.000Z',
  },
  {
    id: 'seed-002',
    documentId: 'CC-SEED-002',
    title: 'Garbage pile blocking a residential lane',
    description:
      'A large pile of mixed waste is accumulated in the residential lane and attracting pests, creating hygiene concerns.',
    category: 'Sanitation',
    department: 'Solid Waste Management',
    pin: '401209',
    locality: 'Residential Lane',
    status: 'Assigned',
    priority: 'Moderate',
    trust: 77,
    chaiHeat: 69,
    supporters: 946,
    reports: 19,
    comments: 28,
    daysUnresolved: 5,
    officer: 'Sanitary Inspector',
    hub: 'Ward Operations Hub',
    createdAt: '2026-08-25T08:30:00.000Z',
  },
  {
    id: 'seed-003',
    documentId: 'CC-SEED-003',
    title: 'Pothole near school boundary road',
    description:
      'A deep pothole at the school boundary is causing risk to children and two-wheeler riders during the morning commute.',
    category: 'Roads & Potholes',
    department: 'PWD — Roads Division',
    pin: '401208',
    locality: 'School Boundary Road',
    status: 'Community Verified',
    priority: 'Critical',
    trust: 92,
    chaiHeat: 94,
    supporters: 2130,
    reports: 41,
    comments: 52,
    daysUnresolved: 12,
    officer: 'Junior Engineer',
    hub: 'Ward Operations Hub',
    createdAt: '2026-08-18T12:15:00.000Z',
  },
  {
    id: 'seed-004',
    documentId: 'CC-SEED-004',
    title: 'Water supply interruption in apartment cluster',
    description:
      'Residents have had no consistent water supply for the last two days, affecting daily needs and sanitation.',
    category: 'Water Supply',
    department: 'Water Works Department',
    pin: '401210',
    locality: 'Apartment Cluster',
    status: 'Filed',
    priority: 'High',
    trust: 79,
    chaiHeat: 76,
    supporters: 1210,
    reports: 22,
    comments: 31,
    daysUnresolved: 2,
    officer: 'Operations Engineer',
    hub: 'Ward Operations Hub',
    createdAt: '2026-08-29T07:00:00.000Z',
  },
]

export const demoIssues = seedIssues
